# Generated by Django 3.2.7 on 2023-07-04 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to=settings.AUTH_USER_MODEL, verbose_name='Преподователь'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule', to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания и время окончание'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала и время начало'),
        ),
    ]
